version: '3.8'

services:
  polymarket-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: polymarket-bot
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config
      - DATA_PATH=/app/data
      # Required: Set your API keys as environment variables
      # - ODDS_API_KEY=${ODDS_API_KEY}
      # - POLY_ADDRESS=${POLY_ADDRESS}
      # - POLY_TIMESTAMP=${POLY_TIMESTAMP}
      # - POLY_API_KEY=${POLY_API_KEY}
      # - POLY_PASSPHRASE=${POLY_PASSPHRASE}
    volumes:
      - ./config:/app/config:ro
      - polymarket_data:/app/data
      - ./logs:/app/logs
    networks:
      - polymarket-network
    healthcheck:
      test: ["CMD", "polymarket_bot", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service if needed
  # sqlite-db:
  #   image: alpine:latest
  #   container_name: sqlite-db
  #   volumes:
  #     - polymarket_data:/data
  #   command: ["sh", "-c", "tail -f /dev/null"]
  #   networks:
  #     - polymarket-network

volumes:
  polymarket_data:
    driver: local

networks:
  polymarket-network:
    driver: bridge 